"""Initial migration

Revision ID: b0380134fca8
Revises: db6c72839f04
Create Date: 2025-04-09 12:07:08.957189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0380134fca8'
down_revision = 'db6c72839f04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appearances', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('episode_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('guest_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('number',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('occupation',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.alter_column('occupation',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.alter_column('number',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('appearances', schema=None) as batch_op:
        batch_op.alter_column('guest_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('episode_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('rating',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
